### ISSUE TITLE
feat: `lib_dir` and `resource_dir` environment variables support

### ISSUE THREAD

**Issue by Cryolitia** [MaaAssistantArknights/maa-cli#67]
Which are written in https://maa.plus/docs/1.6-CLI%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97.html#linux, but actually don't work and can't found in source code anymore.

Search `MaaCore.so` in `LD_LIBRARY_PATH` will be greater.

plus, I'm working on packaging Maa in [Nix User Repo](https://github.com/Cryolitia/nur-packages/blob/master/pkgs/MaaAssistantArknights/default.nix)

**Comment by Cryolitia** [comment]
![image](https://github.com/MaaAssistantArknights/maa-cli/assets/23723294/bc1bc042-a119-4aab-94bb-23d2af3ba09c)
`std::env::current_exe` has platform-specific behavior, which make it worse to just find lib and resource in current_exe's parent directory, when user make a symbol link from `maa.exe` to their Desktop or Startup Menu or so.

**Comment by wangl-cc** [comment]
> `std::env::current_exe` has platform-specific behavior, which make it worse to just find lib and resource in current_exe's parent directory, when users make a symbol link from `maa.exe` to their Desktop or Startup Menu or so.

The main reason we are currently searching for the `lib` and `resource` directories in the parent directory of `current_exe` is to accommodate users who may have installed CLI in various locations, such as `~/.local/bin`. While this approach isn't ideal, it was chosen for its flexibility and as a fallback option.

However, when it comes to package managers, locating the `lib` and `resource` directories becomes much simpler. One potential solution is to introduce a compile time environment variable of `lib` and `resource` path for the package manager. This could potentially present challenges for prebuilt packages, such as Homebrew on Linux, where users have the flexibility to install packages in non-default locations, including within their home directories.

It's worth noting that the necessity for relocatability may vary among different package managers. If other package managers do not require it, this solution could be viable, since installing in non-default locations is discouraged by Homebrew.

> Search `MaaCore.so` in `LD_LIBRARY_PATH` will be greater.

I believe it's a good idea and aligns with the default behaviour of dlopen. I'll delve into this further to explore its feasibility.

**Comment by wangl-cc** [comment]
I just add support for search `LD_LIBRARY_PATH`.

I'm interested in hearing your opinions about the environment variables. @Cryolitia, what are your thoughts on this? And @horror-proton, I'd also like to hear your perspective.

**Comment by horror-proton** [comment]
I guess falling back to system library makes sense.

Perhaps `std::env::current_exe` can be wrapped with something like `realpath` in case it was executed from a symbolic link :thinking:
e.g.:
```
~/.local
├─bin
│ └─maa -> ../stow/maa_cli-0.0.0/bin/maa
└─stow
  └─maa_cli-0.0.0
    └─bin
      └─maa
```
resource should also be in `.local/stow/maa_cli-0.1.2`, not somewhere outside.

**Comment by wangl-cc** [comment]
With the resolution of the `current_exe` issue and the support for searching system libraries, I believe there is no need for additional environment variables. Consequently, I close this issue as completed. Feel free to reopen it if you think it was not resolved.

**Comment by Cryolitia** [comment]
That's great!

with commit https://github.com/MaaAssistantArknights/maa-cli/commit/32c0857066c7a011cf6b3fb0d300fb230f54c8dc , there's also no need for `resource_dir`.

Thanks for your hard work.
